include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 코드 품질
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    cancel_subscriptions: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_statements: true
    exhaustive_cases: true
    hash_and_equals: true
    no_duplicate_case_values: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_string_interpolations: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
